/**
 * 
 */
package ch.heigvd.bachelor.crescenzio.generator.shared;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DatasetsTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public DatasetsTablePageData() {
  }

  @Override
  public DatasetsTableRowData addRow() {
    return (DatasetsTableRowData) super.addRow();
  }

  @Override
  public DatasetsTableRowData addRow(int rowState) {
    return (DatasetsTableRowData) super.addRow(rowState);
  }

  @Override
  public DatasetsTableRowData createRow() {
    return new DatasetsTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return DatasetsTableRowData.class;
  }

  @Override
  public DatasetsTableRowData[] getRows() {
    return (DatasetsTableRowData[]) super.getRows();
  }

  @Override
  public DatasetsTableRowData rowAt(int index) {
    return (DatasetsTableRowData) super.rowAt(index);
  }

  public void setRows(DatasetsTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class DatasetsTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;

    public DatasetsTableRowData() {
    }
  }
}
