/**
 * 
 */
package ch.heigvd.bachelor.crescenzio.generator.shared;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class CreateProject0FormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public CreateProject0FormData() {
  }

  public Author getAuthor() {
    return getFieldByClass(Author.class);
  }

  /**
   * access method for property CreateProject0Nr.
   */
  public Long getCreateProject0Nr() {
    return getCreateProject0NrProperty().getValue();
  }

  /**
   * access method for property CreateProject0Nr.
   */
  public void setCreateProject0Nr(Long createProject0Nr) {
    getCreateProject0NrProperty().setValue(createProject0Nr);
  }

  public CreateProject0NrProperty getCreateProject0NrProperty() {
    return getPropertyByClass(CreateProject0NrProperty.class);
  }

  public Organisation getOrganisation() {
    return getFieldByClass(Organisation.class);
  }

  public PackageName getPackageName() {
    return getFieldByClass(PackageName.class);
  }

  public ProjectName getProjectName() {
    return getFieldByClass(ProjectName.class);
  }

  public static class Author extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Author() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class CreateProject0NrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public CreateProject0NrProperty() {
    }
  }

  public static class Organisation extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Organisation() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class PackageName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public PackageName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class ProjectName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public ProjectName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}
