/**
 * 
 */
package ch.heigvd.bachelor.crescenzio.generator.shared;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class StartFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public StartFormData() {
  }

  public GenerationStatus getGenerationStatus() {
    return getFieldByClass(GenerationStatus.class);
  }

  public static class GenerationStatus extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public GenerationStatus() {
    }
  }
}
