/**
 * 
 */
package ch.heigvd.bachelor.crescenzio.generator.shared;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class CreateProjectFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public CreateProjectFormData() {
  }

  public Author getAuthor() {
    return getFieldByClass(Author.class);
  }

  public Icone getIcone() {
    return getFieldByClass(Icone.class);
  }

  public Organisation getOrganisation() {
    return getFieldByClass(Organisation.class);
  }

  public PackageName getPackageName() {
    return getFieldByClass(PackageName.class);
  }

  public ProjectName getProjectName() {
    return getFieldByClass(ProjectName.class);
  }

  public static class Author extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Author() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MANDATORY, true);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class Icone extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Icone() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class Organisation extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Organisation() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MANDATORY, true);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class PackageName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public PackageName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class ProjectName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public ProjectName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MANDATORY, true);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}
