/**
 * 
 */
package ch.heigvd.bachelor.crescenzio.generator.shared;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class CriteriasTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public CriteriasTablePageData() {
  }

  @Override
  public CriteriasTableRowData addRow() {
    return (CriteriasTableRowData) super.addRow();
  }

  @Override
  public CriteriasTableRowData addRow(int rowState) {
    return (CriteriasTableRowData) super.addRow(rowState);
  }

  @Override
  public CriteriasTableRowData createRow() {
    return new CriteriasTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return CriteriasTableRowData.class;
  }

  @Override
  public CriteriasTableRowData[] getRows() {
    return (CriteriasTableRowData[]) super.getRows();
  }

  @Override
  public CriteriasTableRowData rowAt(int index) {
    return (CriteriasTableRowData) super.rowAt(index);
  }

  public void setRows(CriteriasTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class CriteriasTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;

    public CriteriasTableRowData() {
    }
  }
}
